// <auto-generated />
using BookStore.BookStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20250519092417_SeedBooksData")]
    partial class SeedBooksData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BookStore.BookStore.API.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 20"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 21"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 22"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 23"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 24"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 25"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 26"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 27"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 28"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 29"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 30"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 31"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 32"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 33"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 34"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 35"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 36"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 37"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 38"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 39"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 40"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 41"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 42"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 43"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 44"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 45"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 46"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 47"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 48"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 49"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 50"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 51"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 52"
                        },
                        new
                        {
                            Id = 53,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 53"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 54"
                        },
                        new
                        {
                            Id = 55,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 55"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 56"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 57"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 58"
                        },
                        new
                        {
                            Id = 59,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 59"
                        },
                        new
                        {
                            Id = 60,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 60"
                        },
                        new
                        {
                            Id = 61,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 61"
                        },
                        new
                        {
                            Id = 62,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 62"
                        },
                        new
                        {
                            Id = 63,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 63"
                        },
                        new
                        {
                            Id = 64,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 64"
                        },
                        new
                        {
                            Id = 65,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 65"
                        },
                        new
                        {
                            Id = 66,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 66"
                        },
                        new
                        {
                            Id = 67,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 67"
                        },
                        new
                        {
                            Id = 68,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 68"
                        },
                        new
                        {
                            Id = 69,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 69"
                        },
                        new
                        {
                            Id = 70,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 70"
                        },
                        new
                        {
                            Id = 71,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 71"
                        },
                        new
                        {
                            Id = 72,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 72"
                        },
                        new
                        {
                            Id = 73,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 73"
                        },
                        new
                        {
                            Id = 74,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 74"
                        },
                        new
                        {
                            Id = 75,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 75"
                        },
                        new
                        {
                            Id = 76,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 76"
                        },
                        new
                        {
                            Id = 77,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 77"
                        },
                        new
                        {
                            Id = 78,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 78"
                        },
                        new
                        {
                            Id = 79,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 79"
                        },
                        new
                        {
                            Id = 80,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 80"
                        },
                        new
                        {
                            Id = 81,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 81"
                        },
                        new
                        {
                            Id = 82,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 82"
                        },
                        new
                        {
                            Id = 83,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 83"
                        },
                        new
                        {
                            Id = 84,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 84"
                        },
                        new
                        {
                            Id = 85,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 85"
                        },
                        new
                        {
                            Id = 86,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 86"
                        },
                        new
                        {
                            Id = 87,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 87"
                        },
                        new
                        {
                            Id = 88,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 88"
                        },
                        new
                        {
                            Id = 89,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 89"
                        },
                        new
                        {
                            Id = 90,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 90"
                        },
                        new
                        {
                            Id = 91,
                            Author = "Author 2",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 91"
                        },
                        new
                        {
                            Id = 92,
                            Author = "Author 3",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 92"
                        },
                        new
                        {
                            Id = 93,
                            Author = "Author 4",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 93"
                        },
                        new
                        {
                            Id = 94,
                            Author = "Author 5",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 94"
                        },
                        new
                        {
                            Id = 95,
                            Author = "Author 6",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 95"
                        },
                        new
                        {
                            Id = 96,
                            Author = "Author 7",
                            Genre = "",
                            Price = 11.99m,
                            Title = "Book Title 96"
                        },
                        new
                        {
                            Id = 97,
                            Author = "Author 8",
                            Genre = "",
                            Price = 12.99m,
                            Title = "Book Title 97"
                        },
                        new
                        {
                            Id = 98,
                            Author = "Author 9",
                            Genre = "",
                            Price = 13.99m,
                            Title = "Book Title 98"
                        },
                        new
                        {
                            Id = 99,
                            Author = "Author 10",
                            Genre = "",
                            Price = 14.99m,
                            Title = "Book Title 99"
                        },
                        new
                        {
                            Id = 100,
                            Author = "Author 1",
                            Genre = "",
                            Price = 10.99m,
                            Title = "Book Title 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
